export const ErrorCodes = {
  // Auth
  INVALID_CREDENTIALS: 'AUTH_001',
  ACCOUNT_LOCKED: 'AUTH_002',
  TOKEN_EXPIRED: 'AUTH_003',
  TOKEN_INVALID: 'AUTH_004',
  PASSWORD_TOO_SHORT: 'AUTH_005',
  USERNAME_TAKEN: 'AUTH_006',
  EMAIL_TAKEN: 'AUTH_007',
  CAPTCHA_REQUIRED: 'AUTH_008',
  CAPTCHA_INVALID: 'AUTH_009',

  // Authorization
  FORBIDDEN: 'AUTHZ_001',
  INSUFFICIENT_ROLE: 'AUTHZ_002',
  RESOURCE_NOT_OWNED: 'AUTHZ_003',
  SUPERVISOR_REQUIRED: 'AUTHZ_004',

  // Enrollment
  ENROLLMENT_NOT_FOUND: 'ENROLL_001',
  ENROLLMENT_NOT_DRAFT: 'ENROLL_002',
  ENROLLMENT_NO_SERVICES: 'ENROLL_003',
  SEAT_UNAVAILABLE: 'ENROLL_004',
  SEAT_RESERVATION_EXPIRED: 'ENROLL_005',

  // Order
  ORDER_NOT_FOUND: 'ORDER_001',
  ORDER_ALREADY_PAID: 'ORDER_002',
  ORDER_CANCELED: 'ORDER_003',
  ORDER_AUTO_CANCELED: 'ORDER_004',

  // Payment
  PAYMENT_NOT_FOUND: 'PAY_001',
  PAYMENT_ALREADY_PROCESSED: 'PAY_002',
  REFUND_SUPERVISOR_REQUIRED: 'PAY_003',
  REFUND_INVALID_SUPERVISOR: 'PAY_004',
  REFUND_REASON_REQUIRED: 'PAY_005',

  // Pricing
  PRICING_RULE_NOT_FOUND: 'PRICE_001',
  PRICING_RULE_EXPIRED: 'PRICE_002',
  PRICING_RULE_CONFLICT: 'PRICE_003',

  // Health Check
  REPORT_NOT_FOUND: 'HC_001',
  REPORT_VERSION_LOCKED: 'HC_002',
  REPORT_SIGNATURE_EXPIRED: 'HC_003',
  REPORT_ALREADY_SIGNED: 'HC_004',
  REPORT_SIGNATURE_AUTH_FAILED: 'HC_005',
  REPORT_SLA_BREACHED: 'HC_006',
  PDF_CHECKSUM_MISMATCH: 'HC_007',

  // Content
  ARTICLE_NOT_FOUND: 'CMS_001',
  ARTICLE_SLUG_TAKEN: 'CMS_002',
  ARTICLE_NOT_IN_REVIEW: 'CMS_003',
  SENSITIVE_WORD_DETECTED: 'CMS_004',

  // Notification
  NOTIFICATION_NOT_FOUND: 'NOTIF_001',
  NOTIFICATION_THROTTLED: 'NOTIF_002',

  // Risk
  IP_DENIED: 'RISK_001',
  RATE_LIMITED: 'RISK_002',
  DEVICE_UNTRUSTED: 'RISK_003',
  ANOMALY_DETECTED: 'RISK_004',

  // General
  VALIDATION_ERROR: 'GEN_001',
  INTERNAL_ERROR: 'GEN_002',
  NOT_FOUND: 'GEN_003',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
